# template from spring-boot-1.5.0.RELEASE.jar/org/springframework/boot/logging/logback/defaults.xml, changed to show full thread name
logging.pattern.console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}


# when there's no WebSecurityConfigurerAdapter extension this can be used to change the default username and password for the basic authentication.
#spring:
#  security:
#    user:
#      name : admin
#      password: admin